[package]
name = "scanf"
description = "Macros to parse simple text inputs (inverse of print! and format!)"
version = "0.1.3"
keywords = ["scanf", "sscanf", "stdin", "input", "ffi"]
license = "Unlicense"
authors = ["Jesus Hernandez <jesushdez@protonmail.com>"]
repository = "https://github.com/jhg/scanf-rs"
exclude = [".github/**", ".vscode/**", "Cargo.lock"]
edition = "2021"

[dependencies]
nom = "7.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false
