[package]
name = "scanf"
description = "Parse text inputs (inverse of print! and format!)"
version = "1.1.3"
keywords = ["scanf", "sscanf", "stdin", "input", "format"]
license = "Unlicense"
authors = ["Jesus Hernandez <jesushdez@protonmail.com>"]
repository = "https://github.com/jhg/scanf-rs"
exclude = [".github/**", ".vscode/**", "Cargo.lock", "LICENSE", ".gitignore"]
edition = "2021"

[dependencies]
nom = "7"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false
