name: Security audit

on:
  schedule:
    - cron: "0 0 * * 1" # At 00:00 on Monday.
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  workflow_call:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
