name: Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - ".vscode/**"
      - ".gitignore"
      - "**/*.md"
      - "*.code-workspace"
      - ".github/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - ".vscode/**"
      - ".gitignore"
      - "**/*.md"
      - "*.code-workspace"
      - ".github/**"
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: "0"
  RUST_LOG: debug
  RUSTFLAGS: "-D warnings"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Check
        run: cargo check

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Set up wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
      - uses: Swatinem/rust-cache@v1
      - name: Build tests
        run: cargo test --no-run
      - name: Run tests
        run: cargo test --verbose
